### ISSUE TITLE
[WriteSupport] Write a Dataframe to Neo4j as relationships

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-spark-connector#145]
We want to save a Dataframe as relationships:

```scala
otherFormatDf
   .write
   .format("neo4j")
   .option("relationship", "KNOWS")
   .option("sourceKeys", "source_ssn:ssn") // comma separated list of keys
   .option("sourceLabels", "Person") // comma separated list of labels
   .option("targetKeys", "target_ssn:ssn") // comma separated list of keys
   .option("targetLabels", "Person") // comma separated list of labels
   .save()
```

N.b. in source and target keys you’ll find `source_ssn:ssn` which means:
- `source_ssn` is the column name in the Dataframe
- `ssn` is the node property name

All Dataframe properties that are not in “sourceKeys” and “targetKeys” will be added as relationship properties.

Given the following Dataframe:

source_ssn | target_ssn | since
-- | -- | --
AB12 | CD34 | 2020

Under-the-hood we’ll create the following query:
```cypher
UNWIND batch AS row
MATCH (source:Person{ssn: row.source.source_ssn})
MATCH (target:Person{ssn: row.target.target_ssn})
MERGE (source)-[r:KNOWS]->(target) SET r += row.properties
```

We'll support two SaveMode (https://spark.apache.org/docs/2.4.4/api/java/index.html?org/apache/spark/sql/SaveMode.html):
- `Overwrite`: this will perform a `MERGE` query
- `ErrorIfExists`: this will perform a `CREATE` query

**Comment by moxious** [comment]
Why do this `"source_ssn:ssn"` instead of just having the user pass a map?   Seems like a map might be less syntax error prone, and require less code to process.

I can already easily imagine two new options we're going to need to support here:
* `batchSize` => number of elements per TX to avoid blowing up neo4j memory
* `failOnError` or `failureMode` => say you're going to do 10,000 batches.  Batch number 13 fails.  Do you keep writing, or stop immediately?   Users will want it both ways, configurable.  Default to "quit on first failure"

**Comment by conker84** [comment]
> Why do this `"source_ssn:ssn"` instead of just having the user pass a map? Seems like a map might be less syntax error prone, and require less code to process.

What do you mean about passing a `map`? Can you detail with a simple scenario?

> I can already easily imagine two new options we're going to need to support here:
> 
> * `batchSize` => number of elements per TX to avoid blowing up neo4j memory

Yes we plan to have it.

> * `failOnError` or `failureMode` => say you're going to do 10,000 batches.  Batch number 13 fails.  Do you keep writing, or stop immediately?   Users will want it both ways, configurable.  Default to "quit on first failure"

As first approach I you agree I would like to leverage the spark retry mechanism. Then we can certainly add more options in order to give a more fine-graded control to the developer.

**Comment by moxious** [comment]
We need a relationship keys option too, otherwise "merge" on relationship may run the risk of being meaningless, as is error on create if you don't have a key.   Merge pattern should be something like

```
MERGE (a)-[r:REL { (keys) })->(b) SET r += properties
```

Property-less merge will not support the kind of semantics for idempotent writes that we need.  For example I have a situation where I need to merge relationships by a property "weight".
