### ISSUE TITLE
Applying GraphX alogorthim: PageRank 

### ISSUE THREAD

**Issue by samasalam** [neo4j-contrib/neo4j-spark-connector#331]
For the example shown in (https://neo4j.com/blog/neo4j-3-0-apache-spark-connector/), how could I update it to work using  the new neo4j-spark-connector?  

```
import org.neo4j.spark._

val g = Neo4jGraph.loadGraph(sc, label1="Person", relTypes=Seq("KNOWS"),  label2="Person")

g.vertices.count          
g.edges.count            

import org.apache.spark.graphx._
import org.apache.spark.graphx.lib._

val g2 = PageRank.run(g, numIter = 5)

val v = g2.vertices.take(5)

Neo4jGraph.saveGraph(sc, g2, nodeProp = "rank", relProp = null)

```

**Comment by utnaf** [comment]
You can take a look at the GDS library's Page Rank https://neo4j.com/docs/graph-data-science/current/algorithms/page-rank/

And look at this page of the documentation https://neo4j.com/developer/spark/gds/

I suggest you to look at the documentation before opening issues since it's very exhaustive and you find examples for most scenarios.
