### ISSUE TITLE
Bintray shutting down  -  plan for maven2

### ISSUE THREAD

**Issue by asethia** [neo4j-contrib/neo4j-spark-connector#334]
Hi,

As we know 

"JFrog announced that they will be shutting down Bintray and JCenter. A complete shutdown is planned for February 2022"

Any plan to move Maven 2 repository?

Thanks

**Comment by moxious** [comment]
Need access to correct code signing keys from engineering to get this done and we will look into a TeamCity job which may delegate this

**Comment by utnaf** [comment]
Hi there! Closing the issue because now the Neo4j Connector for Apache Spark is available on maven 🎉 

https://search.maven.org/search?q=g:org.neo4j%20AND%20a:neo4j-connector-apache-spark_2.12
https://search.maven.org/search?q=g:org.neo4j%20AND%20a:neo4j-connector-apache-spark_2.11

You can follow the instructions on the documentation https://neo4j.com/developer/spark/quickstart/#_using_maven

**Comment by asethia** [comment]
@utnaf  Thanks for the quick release.
