### ISSUE TITLE
Add a way to pass cypher parameters to read queries

### ISSUE THREAD

**Issue by pecollet** [neo4j-contrib/neo4j-spark-connector#429]
## Feature description (Mandatory)
Currently when reading from neo4j with a cypher query, there's no way to cleanly pass in [parameters](https://neo4j.com/docs/cypher-manual/current/syntax/parameters/) to the query.

ex :

```
spark.read.format("org.neo4j.spark.DataSource")
  .option("url", "bolt://localhost:7687")
  .option("query", "MATCH (n:Person) WHERE n.name=$filter RETURN id(n) AS id")
  .load()
```

That could be implemented as an extra `.option("query.param", ...)`.
Note : that feature could also apply to "write" queries, although they already have access to the `event` data from its source dataset. 

## Considered alternatives
Currently, one has to concatenate data in the query string (vulnerable to cypher-injection) or bypass the connector and use the neo4j driver directly.

## How this feature can improve the project?
Parameterised cypher queries are a very common way to select data to read from neo4j. Their usage should be made easy and safe.

**Comment by moxious** [comment]
@pecollet you're partially running into limitations of the Spark DataSource API.   While you could have an `.option("query.param")` I believe there are some limitations on data types you can pass this way; they're generally strings.  So if you wanted to pass an integer (or god forbit a geospatial point) you'd end up having to send a param string and then putting extra cypher in there to do type conversion.

Part of how spark thinks about these things is that it's spark's job to do things like filtering, so it isn't necessarily set up to be friendly to pass off such operations to other data layers.  For example in this case, you could just do that query without the filter, and then take the resulting dataframe and filter it using the spark dataframe API.  Yes, this would fetch too much data from Neo4j and yes I'm aware that's not a wonderful solution, it's just typically how you'd think about problems like this with spark, is "use spark to do that", much like Neo4j isn't good at passing filters to non-Neo4j data processing layers.

Lastly -- "Cypher query" through the datasource API is (from spark's perpsective) a bit of a work-around.  What makes the connector convenient to use is its DataSource API compliance.  What customers are trying to do here is to use the spark connector as a fully-fledged Neo4j driver, and that's probably going to be awkward.   Parameter submission is a perfectly reasonable expectation of the neo4j driver, but then so is explicit transactions and many other features that may be hard to surface via a connector.

There's another way you can approach this too.  In the example you only need people.  You can read by label, and then use .filter() in spark to filter to only those with the name.  Spark connector supports limited "pushdown filters" (see setting pushdown.filters.enabled here https://neo4j.com/docs/spark/current/reading/#_neo4j_read_options).   This is a "no cypher" option of accomplishing the same.  Again, it's all about using spark, rather than trying to use Neo4j through spark.

**Comment by lvijnck** [comment]
Would like to "spark" discussion here again.. :)

While I agree the pushdown projection is useful, I like my workflows to actually start off with a proper Cypher query.
