### ISSUE TITLE
Example of use with PySpark

### ISSUE THREAD

**Issue by ajmazurie** [neo4j-contrib/neo4j-spark-connector#8]
Hi, I was wondering if an example of use of **neo4j-spark-connector** with **PySpark** could be added to the documentation? PySpark is mentioned in the README, but there are no associated examples.

Best, Aurélien

**Comment by jexp** [comment]
Great question.  I'm not sure if the scala code can be used from
Python. But it should be equally easy to query neo4j from
PySpark using the neo4j-python-driver 

Von meinem iPhone gesendet

**Comment by ajmazurie** [comment]
The issue with that is the need to pickle/unpickle whatever driver across Spark jobs. I couldn't get it to work with **py2neo** for example.

**Comment by zhiboz** [comment]
I think we would need a thin python wrapper in order to use this in pySpark, similar to 

https://github.com/graphframes/graphframes/blob/master/python/graphframes/graphframe.py

which allows us to use `graphframes` in pySpark.

**Comment by ikwattro** [comment]
The problem is that the SparkContext in the spark connector is not compatible if you want to use it in pyspark. There are multiple solutions until we can adapt neo4j-spark-connector with pyspark : 

1) use the neo4j-driver and creates rdd's from the results (drawback : as you cannot create custom datasources in python you loose the streaming benefits from the neo4j-driver :( )

2) use two modules : 

a) from the neo4j-driver pass results over to kafka
b) from pyspark read kafka

benefits : very performant and streamed all the way

3) use two contexts in pyspark : very headache prone solution but I could make it work once, I wouldn't do it again

**Comment by jexp** [comment]
What @ikwattro said.

**Comment by N-CP** [comment]
how I can connect neo4j with pyspark???
I have py2neo driver and neo4j-driver

**Comment by suyash248** [comment]
Could anyone please share the appropriate approach/solution to this problem?

**Comment by mitakshgupta** [comment]
Is neo4j-spark-connector compatible with spark now?

**Comment by JakobWyatt-VGW** [comment]
For anyone having this issue, the link here is incredibly helpful: https://diogoalexandrefranco.github.io/scala-code-in-pyspark/
